struct Environment
    seed::Int64
    instance::String
    max_generations::Int64
    max_time::Int64
    population_size::Int64
    n::Int64
    m::Int64
    s::Int64
    A::Matrix{Float64}
    encoding::String
    initialization_method::String
    selecion_method::String
    parent_selection_method::String
    mutation_method::String
    mutation_probability::Float64
    crossover_method::String
    crossover_probability::Float64
    elite_size::Float64
    offspring_size::Float64
end